### PR TITLE
Retargeting to DS 701

### PR DESCRIPTION
**Pull request by Farid-Karimli**

### CODE REVIEW

**Review by trgardos — CHANGES_REQUESTED** [review]
Please changre the GH actions yaml to target a space at https://huggingface.co/tools4ds so the dl4ds doesn't get overwritten.

**Comment by trgardos** [comment]
Also I see one CI code quality issue was flagged.

**Comment by Farid-Karimli** [comment]
Yeah, I think changing it to accept args for the host and port will solve it. 

> Also I see one CI code quality issue was flagged.

**Comment by Farid-Karimli** [comment]
I changed the workflow target and added command line args for running the server, but the code quality check failed anyway.

**Review by trgardos — APPROVED** [review]

**Comment by trgardos** [comment]
> Yeah, I think changing it to accept args for the host and port will solve it. 
> 
> 
> 
> > Also I see one CI code quality issue was flagged.
> 
> 
> 
> 

How was it set in dl4ds_tutor?

**Comment by Farid-Karimli** [comment]
> > Yeah, I think changing it to accept args for the host and port will solve it.
> > > Also I see one CI code quality issue was flagged.
> 
> How was it set in dl4ds_tutor?

It was set as 0.0.0.0 but the code checks passed

**Pull request merged**
